### ISSUE TITLE
Disabling or uninstalling the plugin does not remove the colour tags

### ISSUE THREAD

**Issue by wallali** [jenkinsci/ansicolor-plugin#122]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: 2.112
- AnsiColor Version: none
- Hostsystem: linux

### Expected behavior
No ansi colour tags should be included in the output

### Actual behavior

Despite turning off and uninstalling the plugin the console output is still showing colour tags (freestyle project)
` ?[32m  ․?[0m?[90m Returns error if no property was found: ?[0m?[90m0ms?[0m`

### Steps to reproduce the behavior
- Enable the plugin
- Disable the plugin

Please provide small but complete code, e.g. shell script and / or Jenkinsfile.

**Comment by amir-barkal** [comment]
Experiencing the same behavior on Jenkins 2.107

**Comment by melezov** [comment]
Our Jenkins crashed because of trying out the plugin and the uninstalling it as it's still visible in all logs... Usually a 11x enlargement per output line - from 100 MB to 1.1GB ... :(

**Comment by dblock** [comment]
I think the problem is that the logs are written with ansi color DIVs added to it. I could be wrong, but there's no other way to do this in Jenkins.

**Comment by tszmytka** [comment]
There are 2 separate things here:
I. "still showing colour tags"
> Despite turning off and uninstalling the plugin the console output is still showing colour tags (freestyle project)
`?[32m ․?[0m?[90m Returns error if no property was found: ?[0m?[90m0ms?[0m`

The `ESC[32m` escape sequences are produced by the build script you are running and **not** by `ansicolor`. The plugin is responsible for interpreting and rendering them in html.

II. "build logs get very large"
> makes our build logs grow to a whopping size in GBs...
> Usually a 11x enlargement per output line

This was an issue with `ansicolor` before `v0.7.0`. It used to annotate each line with a 'ConsoleNote`. Since `v0.7.0` this is no longer the case - 'ConsoleNote`s are still used but sparingly. A usual build will annotate 2-3 lines.
