### ISSUE TITLE
Control characters appearing in job output in 0.6.0

### ISSUE THREAD

**Issue by nosmo** [jenkinsci/ansicolor-plugin#145]
I'm seeing control characters show up in coloured job output where previously there were none before. It seems that this could be somewhat related to #141.

### Test environment

- Jenkins Version: 2.148
- AnsiColor Version: 0.6.0
- Hostsystem: Debian stretch

### Expected behavior

Up until 0.6.0 I would only occasionally see `[0m` characters show up and they did not affect output. The following appears when testing against 0.5.3

![screen shot 2018-12-20 at 16 22 06](https://user-images.githubusercontent.com/68673/50296909-6c864600-0473-11e9-9c78-44c1a8913296.png)

### Actual behavior

With 0.6.0 I now see more control characters and in some cases no colour output at all: 

![screen shot 2018-12-20 at 16 08 49](https://user-images.githubusercontent.com/68673/50296947-86278d80-0473-11e9-9924-73abbe9819c5.png)

In more complex jobs with more varied colour output, the colour output will not be properly bounded and will leak into following lines. 

### Steps to reproduce the behavior

The above outputs were reproduced by running the following job using the pipeline library: 
```
def label = "terraform-${UUID.randomUUID().toString()}"

podTemplate(label: label, inheritFrom: 'jnlp', containers: [
  containerTemplate(
      name: 'terraform',
      image: 'hashicorp/terraform',
      ttyEnabled: true,
      command: 'cat',
      alwaysPullImage: true,
  )
]) {
    node(label) {
        container('terraform'){
            ansiColor('xterm') {
                sh """
                 terraform plan
                """
            }
        }
    }
}
```

**Comment by choppedpork** [comment]
I'm seeing the same issue - incidentally first spotted in a terraform build as well however this also happens when executing ansible-playbook jobs:
![image](https://user-images.githubusercontent.com/11997044/50521579-45a4c100-0abe-11e9-978c-058cf31aa4b9.png)

**Comment by kapoorlakshya** [comment]
Seeing the same in console output from Cucumber. Rolling back to `v0.5.3` works for now. Not a 100% sure, but I think this was introduced by #132.

**Comment by dwnusbaum** [comment]
Yes this was probably introduced by #132. If anyone is able to create a PR with a minimal failing test case similar to the tests in [AnsiColorBuildWrapperTest](https://github.com/jenkinsci/ansicolor-plugin/blob/master/src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java) it would help us understand the core part of the problem. Might be similar to #135, so I would be interested to see if something like #137 would help.

**Comment by cloos** [comment]
See also https://issues.jenkins-ci.org/browse/JENKINS-55139

**Comment by dwnusbaum** [comment]
I attached a custom snapshot build of the plugin to [JENKINS-55139](https://issues.jenkins-ci.org/browse/JENKINS-55139) based on `master`, which includes #137. If anyone seeing the issue can test that snapshot and let me know whether it helps, that would be great.

**Comment by jrudolph** [comment]
Still broken for us with the custom version attached to JENKINS-55139. Had to downgrade to 0.5.3.

E.g. broken: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14436/console
With 0.5.3: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14437/console

**Comment by dwnusbaum** [comment]
Thanks for the links @jrudolph. I am not able to reproduce a failure in quite the same way unless I disable colorized output from the job's configuration page, although perhaps the appearance has degraded even further that it looked originally when you were running 0.6.0, because 0.5.3 does not understand the log format used in 0.6.0, so that might explain the discrepancy. I took a line from your logs and did some local testing to reproduce the issue.

Here are the 3 variants of the issue that I am seeing:

1. Escape sequences are completely ignored. This is what I see running ansicolor 0.6.0, building a freestyle project with colorized output disabled (this is what your logs look like, and could perhaps be reproduced by running a freestyle job in ansicolor 0.6.0 with colorized output enabled, downgrading to ansicolor 0.5.3, and viewing the log again):
<img width="599" alt="screen shot 2019-01-09 at 15 04 37" src="https://user-images.githubusercontent.com/1068968/50928269-3f9cd180-1428-11e9-965f-2ad9924d8562.png">

2. Escape sequences are not completely ignored, but they some of them show up in the logs incorrectly and some log text is incorrectly being hidden. This is what I see running ansicolor 0.6.0, building a freestyle project with colorized output enabled:
<img width="391" alt="screen shot 2019-01-09 at 15 04 12" src="https://user-images.githubusercontent.com/1068968/50928283-462b4900-1428-11e9-943f-1fa930501934.png">

3. Escape sequences are handled correctly. This is what I see with a local fix for variant 2 of the issue (matching the appearance with ansicolor 0.5.x):
<img width="379" alt="screen shot 2019-01-09 at 15 07 03" src="https://user-images.githubusercontent.com/1068968/50928293-4b889380-1428-11e9-8754-9ebbd0d9ac51.png">

It would be very helpful to understand if you and other users are seeing variant 1 or variant 2 **for builds built when running ansicolor 0.6.0 while ansicolor 0.6.0 is still installed** (not after downgrading to 0.5.3 and looking at logs for builds run under version 0.6.0). If you are seeing variant 1, then I have no idea what is going on, but if you are seeing variant 2 then I know how to fix the problem.

For anyone seeing variant 1 of the issue, are you running Freestyle or Pipeline jobs? Are there any error messages in your Jenkins logs when you view the console output for a job? If it is a freestyle job, is colorized output enabled?

**Comment by jrudolph** [comment]
It seems it's variant 2 here.

**Comment by dwnusbaum** [comment]
@jrudolph Thanks for the update, in that case I think #147 should help. I'll try to attach a snapshot build to the Jira ticket soon so anyone experiencing the issue can see if it helps.

**Comment by JoeyG1973** [comment]
I am noticing that it has something to do with the here document like stuff when you call things. 
```
sh """
terraform apply
"""
```

**Comment by oxygenxo** [comment]
I have similar issues on Jenkins 2.150.2 and 0.6.1

**Comment by oxygenxo** [comment]
@dwnusbaum it works like a charm, thank you!

**Comment by kapoorlakshya** [comment]
Hi @dwnusbaum, the fix in v0.6.2 is only partially working when using Cucumber. What I mean by partially is that I still see the ASCII characters and no colors in the console output as the text shows up. However, when I refresh the page the ASCII characters disappear and the text shows up in color. 

This behavior is not experienced in v0.5.3. Also, this only happens in the console output and not in the Blue Ocean view.

Before refresh:

![image](https://user-images.githubusercontent.com/4314581/52154485-e42ebf80-2632-11e9-9bb7-7bda260698cf.png)


After page refresh:

![image](https://user-images.githubusercontent.com/4314581/52154497-f01a8180-2632-11e9-8e66-e7db76663725.png)

Raw output:

```
[32mAnd I access the '[32m[1mSearch[0m[0m[32m' [32m[1mtab[0m[0m[32m[90m
```

Cucumber command:

```
bundle exec cucumber -t @search_page -f json -o cucumber.json -f pretty --color --expand
```

**Comment by dwnusbaum** [comment]
@kapoorlakshya @fgnathan That sounds like #136, but I don't have any ideas about the cause. It would be great to add any additional reproduction information or diagnostics to that ticket (perhaps it is related to size of the logs, whether the logs are truncated, etc.) to help us understand what is happening.

**Comment by ulich** [comment]
I also see this issue

It happens with very little amount of logs, so no truncating.
In our case, there are commands in the pipeline definition before, that do not have any ANSI color output. 

Maybe that helps

**Comment by dwnusbaum** [comment]
Thanks for the info @ulich, but let's try to keep any discussion about that issue in #136 for clarity.

**Comment by kapoorlakshya** [comment]
@dwnusbaum Thanks! I will add all relevant information in that issue.

**Comment by fearnycompknowhow** [comment]
It seems that Terraform attempts to format the output using color.  However, Jenkins does not output this formatting correctly and thus you see those unusual characters in the output.

Thanks to [this thread](https://github.com/hashicorp/terraform/issues/12305), I was able to make Terraform omit those characters in the output by using the `-no-color` flag.

This options is available for at least three of the major Terraform functions: `show`, `plan`, and `apply`.  It's probably be available for others, I just haven't confirmed it.
