### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by quasarea** [jenkinsci/ansicolor-plugin#148]
### Test environment

- Jenkins Version: 2.150.1
- AnsiColor Version: 0.6.1
- Hostsystem: Windows 10

Declarative pipeline, 

    pipeline {
        agent {
            node {
		    label params.node
                customWorkspace new File("${JENKINS_HOME}\\Workspace\\${URLDecoder.decode(JOB_NAME)}").toString()
            }
        }

        options {
            buildDiscarder(logRotator(numToKeepStr:'10'))
            timeout(time: 60, unit: 'MINUTES')
            timestamps()
            ansiColor('xterm')
        }
        ...
    }

Produces quite long output (up to 30mb - msbuild/xunit)

Getting same error for different cases (in different locations depending on output length):

    java.lang.StackOverflowError
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:114)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
	...

In one case it was thrown after 39564 character, in other after 28055

After taking ansiColor('xterm') out, it works fine

**Comment by dwnusbaum** [comment]
I would be surprised if this is related to AnsiColor. Do you have the full stack trace? It looks like an issue somewhere in core Pipeline serialization code.

**Comment by dwnusbaum** [comment]
If you have further information that points to this being caused by `ansicolor`, feel free to reopen, but I think the fact that removing `ansicolor` makes things work is probably just a fluke and the error is either in workflow-support or JBoss Marshalling itself, see https://issues.jenkins-ci.org/browse/JENKINS-52966, although the fact that removing it fixed the problem leads me to believe that possibly this is not infinite recursion, but that some changes in JBoss Marshalling have increased the number of recursive calls that are made under normal circumstances.
