### ISSUE TITLE
"Global color map for all builds" not working for pipelines

### ISSUE THREAD

**Issue by benbrummer** [jenkinsci/ansicolor-plugin#174]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: 2.204.5
- AnsiColor Version: 0.6.3
- Hostsystem: Ubuntu 18.0.4 LTS

### Expected behavior
Global color map for all builds (Jenkins=>Settings=>ANSI Color) is working in pipelines
Screenshots are welcome.

### Actual behavior

Colors are not displayed.

### Steps to reproduce the behavior

Set "xterm" as Global color map for all builds. It is not working in pipeline builds.

**Comment by tszmytka** [comment]
Thank you for the report.

Are you sure about those version numbers? If so, it seems to me you are running a pretty outdated version of `Jenkins` (from what I can tell version `2.20.5` is from somewhere around December 2016) as well as `ansicolor-plugin` (January 2019).

More importantly, the _Global color map for all builds option_ you're referring to, has been added only since ansicolor-plugin `0.6.3`.

Please update Jenkins to a more recent version and the plugin to the newest possible one (currently `0.6.3`). There have been a lot of changes in the mean time and your bug might have already been fixed.

**Comment by benbrummer** [comment]
I updated my description with the correct versions.

**Comment by tszmytka** [comment]
I still cannot reproduce this. The following combination works fine and is able to render colored output in the logs no matter what _Global color map for all builds_ is set to (tried `[nothing]`, `xterm` and `asdf`). If it is incorrect the default `xterm` kicks in.
```
Jenkins ver. 2.204.5
AnsiColor 0.6.3
```

Something else has to be the reason. Could you please:
1. Provide a screenshot of your *Configure Jenkins* page with the **ANSI Color** area showing all the settings you have there.
2. Paste an example of a pipeline you are using. Could be 1-2 steps which normally produce colored output. A screenshot with from your Jenkins' console output would also be nice.
3. If you have access to shell - provide content of the following file located in `$JENKINS_HOME`
`hudson.plugins.ansicolor.AnsiColorBuildWrapper.xml`.

**Comment by benbrummer** [comment]
When i tried to reproduce this issue now by removing the ```options { ansiColor('xterm') }``` from the pipelinescript, everything still works as it should . I guess i faced a layer 8 Problem on my side. @tszmytka Thank you for your support.
