### ISSUE TITLE
artifact text files not honoring formatting (enhancement?)

### ISSUE THREAD

**Issue by borisivan** [jenkinsci/ansicolor-plugin#187]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version: 2.237
- AnsiColor Version: 0.7.0
- Hostsystem: centos container

### Expected behavior
What did you expect the plugin to do?
Our build system saves the maven output to a file which is included as an archived file re: archive the artifacts. That file has all the xterm formatting, but when viewing those files through Jenkins we see all the escape codes, making the text illegible. We were expecting to see the files rendered honoring the xterm formatting.

Screenshots are welcome.

### Actual behavior
What did the plugin do instead?
As described above.

Screenshots are welcome.

### Steps to reproduce the behavior
Archive an artifact that is a text file that would have otherwise been the console output. If it is console output viewed in a pipeline stage, ansicolor shows it correctly. But if that is a text file as an artifact, no formatting is honored in the jenkins display of that artifact.

I understand this might be an enhancement, maybe the plugin was never intended to be utilized when also looking at those artifacts. And maybe it might require an optional link, so that the user could click on a link that honors the formatting, versus clicking a link that doesn't, not sure what the best approach is.

**Comment by tszmytka** [comment]
It seems that you are viewing a text file (doesn't matter if it contains a copy of STDOUT or anything else) and expecting `ansicolor` plugin behavior to kick in. This is not how it was intended to work.

The plugin taps into `Jenkins` internal functionality for rendering logs - that's why it works for pipeline stage output as well. Your use case _might_ technically work it you managed to "convince" `Jenkins` that your file is a logfile but I've never tried that myself. What's more - `ansicolor` needs metadata stored in each build - the output alone is not enough.

Could you share a little bit of background information?
Why do you need to store the output *separately*? `Jenkins` does that out-of-the-box.
If you published the link to your job's output, something like:
```
/job/<your-job-name>/<run-id>/console
```
wouldn't it be the same?

**Comment by borisivan** [comment]
Hi @tszmytka thanks for the response.

The files I am referring to are generated during a build and in this case, not part of the console output. But they have standard xterm ansi color coding. Since they are not part of the console output of this particular build, we 'archive the artifacts' for these files and that works great, other than the fact that they are illegible.
