### ISSUE TITLE
Support Powershell console colors

### ISSUE THREAD

**Issue by neilknowscomputers** [jenkinsci/ansicolor-plugin#39]
Powershell supports colors in its console output similar to other shells a la

`Write-Host "Blue on Green!" -ForegroundColor Blue -BackgroundColor Green`

It would be pretty freaking awesome if [Powershell scripts run in Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/PowerShell+Plugin) would display these output color choices. I am not a Java developer personally, but if this is easy enough to do I could take a swing at it. I could certainly test the feature if someone else implemented it.

**Comment by ejelly** [comment]
It's more about bringing PowerShell to output the proper color escape codes, which the ansicolor plugin would interpret and translate into HTML. I'm not sure if that's possible, a quick search lead to nothing obvious. It may very well be that the PowerShell drives the Windows Terminal directly with some API when run within it, instead of outputting escape codes which would then be parsed.

You can do the research to see if PowerShell can color its output using escape codes. If it can, then you might be lucky in that ansicolor supports them already. If there are unsupported ones, we might take shot at implementing them. But as said, that all depends on PowerShell actually outputting the color information.

**Comment by Stefan-Hanke** [comment]
No it doesn't. I checked this by putting that line of PowerShell script into a file and ran the equivalent of **powershell ./test.ps1** and observed the output. It's just the raw characters, no escape sequences whatsoever.

Just digging around a little bit:

The solution depends on whether one can write escape sequences to standard output at all. If true, the simplest solution is to replace calls to `Write-Host` with a custom function, emitting the proper escape sequences. If you can't change the code, there is a way to change what `Write-Host` does [via cmdlet proxies](https://byteonmyside.wordpress.com/2012/04/25/how-to-capture-or-redirect-write-host-output-in-powershell/).

Even easier seems to just redefine `Write-Host` to a function that internally uses `Write-Output`. Might be worth a shot. Seen on SO somewhere but alas lost the link...
> function global:Write-Host() { }

Mayhaps the scripts could be wrapped before execution...

**Comment by vzabauski** [comment]
There's a workaround.
http://stackoverflow.com/questions/39296240/use-ansicolor-in-jenkins-via-powershell
