### ISSUE TITLE
Some output isn't interpreted correctly

### ISSUE THREAD

**Issue by ulope** [jenkinsci/ansicolor-plugin#53]
I've got a problem where the plugin doesn't correctly render the output of a python library (`pytest-sugar`, a plugin to `pytest`). 

As you can see from the screenshots below some of output is rendered correctly but the main block is showing up in raw escape sequences.

![a](http://f.cl.ly/items/1R291F273I1E2L2f3F1V/Image%202015-06-29%20at%205.24.09%20nachm..png)
_...snip..._
![b](http://f.cl.ly/items/203C3C351t132R3p2W1Q/Image%202015-06-29%20at%205.24.29%20nachm..png)

The "correct" output in a terminal looks like this: 
![more like this](http://f.cl.ly/items/1z3J0I1E1c2D2C0b1K2w/Screen%20Shot%202015-06-29%20at%2017.02.35.png)

[Here is the complete Jenkins output](http://cl.ly/text/0i1U2L3t3v2s)

The above was generated from the following minimized example:

``` shell
cd ${WORKSPACE}
cat << EOF > test_blah.py
import time
import pytest

@pytest.mark.parametrize("i", list(range(20)))
def test_blah(i):
    time.sleep(.5)
EOF

pip install pytest pytest-sugar
py.test --color=yes test_blah.py
```

This should be run inside a "Virtualenv Builder" (nature: "shell") from the "ShiningPanda" Jenkins plugin.

**Comment by dblock** [comment]
Related: https://github.com/dblock/jenkins-ansicolor-plugin/issues/47

**Comment by dblock** [comment]
Could be related to https://github.com/dblock/jenkins-ansicolor-plugin/issues/16.

**Comment by JoeMerten** [comment]
I'd tested this using Jenkins 1.653, AnsiColor 0.5.0 on Kubuntu 16.04 host. In meantime, my versions of python, pytest et cetera are a bit higher than yours. Linux terminal output:
<kbd>![screenshot_20170321_152004](https://cloud.githubusercontent.com/assets/6552470/24151790/039f35be-0e4a-11e7-9a32-2438e11990d7.png)</kbd>

Jenkins output:
<kbd>![screenshot_20170321_151346](https://cloud.githubusercontent.com/assets/6552470/24151492/3fd39512-0e49-11e7-8475-0125dd7df302.png)</kbd>

As we can see, the output is ok readable but a bit different formatted. This is because of the command detects Jenkins' output redirection (to non terminal) and adapts it's behavior. We can see similar, when redirecting on console:
<kbd>![screenshot_20170321_153019](https://cloud.githubusercontent.com/assets/6552470/24152241/58204e88-0e4b-11e7-964e-e707360fd1b9.png)</kbd>

In the next test scenario, I tried to force `py.test` more sugar using the `--force-sugar` option:

    $ py.test --color=yes --force-sugar test_blah.py

which gave the same result as without  `--force-sugar` option, as long as executed on a real terminal. But the output of `py.test` became buggee when using `--force-sugar` and also do output redirection. So might try this to see what happen:

    $ py.test --color=yes --force-sugar test_blah.py | tee output.txt

<kbd>![screenshot_20170321_154314](https://cloud.githubusercontent.com/assets/6552470/24152867/2cdd55e8-0e4d-11e7-9baf-b0fb2311f5b6.png)</kbd>

Checking the content of `output.txt` we see, that py.test has generated some output were e.g. the escape characters (ascii 27 = 0x1B) were translated to each 4 characters `\` `x` `1` `b`.

So finally, it's a bug in `py.test` or `pytest-sugar` and there is unfortunately nothing what AnsiColor can help for.
