### ISSUE TITLE
log files get bloated with "junk" data 

### ISSUE THREAD

**Issue by higrow** [jenkinsci/ansicolor-plugin#67]
Hi, first of all thanks for you work on this plugin. 

With the AnsiColor Plugin enabled our logfiles are getting huge with coloured output enabled. 
In particular every line that has color sequences will add "junk" data to it, giving me: 

`Default [8mha:AAAApR+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDDI2RQXJOYpFJdU5qTaKoEttlJQdnYxMHB2sVayAwDjW+2vpQAAAA==[0mMagenta[8mha:AAAAkR+LCAAAAAAAAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDCw2+gXFyTm2QEAI9P8iI4AAAA=[0m
`

instead of (with color output disabled): 

`Default [35mMagenta[0m`

for the script:

``` bash
#!/bin/bash 
echo -e "Default \e[35mMagenta\e[0m"
```

I reproduced this on Debian Wheezy with the official jenkins repository (and java 7) in stock configuration to rule out a problem with our setup. 

same problem was discussed in the comments here: https://issues.jenkins-ci.org/browse/JENKINS-11752

do you have any idea what could cause this and a possible solution / workaround? 

thanks in advance.

**Comment by dblock** [comment]
I've seen something similar before, it's some kind of out of band data that Jenkins spews and uses. I would try to get a raw output log first, this data is there, it just gets properly stripped out of the output by Jenkins and incorrectly handled by the plugin.

**Comment by dblock** [comment]
https://github.com/dblock/jenkins-ansicolor-plugin/issues/30 could be related and has some explanation

**Comment by higrow** [comment]
thanks for the quick response. 

the problem in my case is not related to the frontend, the display in the frontend is fine. 
the mangled data is just in the build log file, leading to huge logfiles. 

i attached 2 files, 1 without the plugin, 1 with the plugin enabled.

[color.txt](https://github.com/dblock/jenkins-ansicolor-plugin/files/158854/color.txt)
[plain.txt](https://github.com/dblock/jenkins-ansicolor-plugin/files/158853/plain.txt)

**Comment by MartinNowak** [comment]
Oh dear, ansicolor is using Jenkins' ConsoleNote feature to hardcode the html `<span color="bla">` snippets into the text [¹](https://github.com/dblock/jenkins-ansicolor-plugin/blob/dc3d72645e2e78ff46e8b30b96b85eb178811a9c/src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java#L41-L43) [²](https://github.com/dblock/jenkins-ansicolor-plugin/blob/d4fdaf780ef09b592dc3c371e26b1dc9de145efb/src/main/java/hudson/plugins/ansicolor/SimpleHtmlNote.java).
Those ConsoleNotes get encoded and compressed [¹](https://github.com/jenkinsci/jenkins/blob/c0344d4de93292d74203e47b3b10366559315308/core/src/main/java/hudson/console/ConsoleNote.java#L92-L94). The jenkins docs explicitly warn you to not emit too much data [¹](https://github.com/jenkinsci/jenkins/blob/c0344d4de93292d74203e47b3b10366559315308/core/src/main/java/hudson/console/ConsoleNote.java#L103).
Isn't there a way to render the log output to html when displaying it? Rather than encoding the html w/ such a weird mechanism into the log file.

**Comment by dblock** [comment]
@MartinNowak If you find a better way we'd love a PR!

**Comment by MartinNowak** [comment]
> @MartinNowak If you find a better way we'd love a PR!

Well, can you get into the presentation of the log files? Processing the whole log before it's rendered would be the best option. Who is even responsible to decode and write the ConsoleNote html snippets into the html output?
If I get this right, there is [AnsiHtmlOutputStream](https://github.com/dblock/jenkins-ansicolor-plugin/blob/dc3d72645e2e78ff46e8b30b96b85eb178811a9c/src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java#L48) which gets fed the output of the jenkins job containing ASCI codes. These codes are interpreted and converted into [AnsiAttributeElement](https://github.com/dblock/jenkins-ansicolor-plugin/blob/dc3d72645e2e78ff46e8b30b96b85eb178811a9c/src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java#L15) (to keep track of begin and end of text properties, e.g. color, bold etc.). Because ANSI codes can do things like reset, there is not a 1-to-1 relation between ASCI codes and AnsiAttributeElement, hence the openTags list in AnsiHtmlOutputStream.
Now the problem starts when those AnsiAttributeElements are converted into opening/closing html tags and get [emitted](https://github.com/dblock/jenkins-ansicolor-plugin/blob/dc3d72645e2e78ff46e8b30b96b85eb178811a9c/src/main/java/hudson/plugins/ansicolor/AnsiColorBuildWrapper.java#L213) as [SimpleHtmlNote](https://github.com/dblock/jenkins-ansicolor-plugin/blob/dc3d72645e2e78ff46e8b30b96b85eb178811a9c/src/main/java/hudson/plugins/ansicolor/SimpleHtmlNote.java#L10) to the stream. This effectively adds bloated html output to the on disk log format (and it's blown up even further by the compression and base64 encoding).
Later when the disk format is read (e.g. to view a build log), all ConsoleNotes get decoded from the concealed parts in the ondisk format, and their annotate method gets called with the position and current line. SimpleHtmlNote.annotate uses this to inject the previously generated html snippet.

Now the obvious solution here is to encode only the ascii codes (and maybe the ascii code state) in a ConsoleNote as small as possible. Those can later be converted to html tags by the ConsoleNote.annotate method. Apparently a similar approach was already taken with [AnsiColorNote](https://github.com/dblock/jenkins-ansicolor-plugin/blob/d47d7f6d6b11ff827032bd643ca1e0b46c59c616/src/main/java/hudson/plugins/ansicolor/AnsiColorNote.java#L39) in <0.4. Not sure what the reason for the change were.

Looking at the [documentation of ConsoleNote](http://javadoc.jenkins-ci.org/hudson/console/ConsoleNote.html) there seems to be another compeling possibility, a ConsoleAnnotator (sth. that can be used on all text ConsoleAnnotatorFactory, or be returned from a ConsoleNote) can keep internal state and is used to highlight multiple lines. So it should be possible to just leave the raw ANSI codes in the on-disk log and add a [ConsoleAnnotator (Jenkins main module 2.4 API)](http://javadoc.jenkins-ci.org/hudson/console/ConsoleAnnotator.html) (via [ConsoleAnnotatorFactory](http://javadoc.jenkins-ci.org/hudson/console/ConsoleAnnotatorFactory.html)) that converts them to html on the fly.

If raw ANSI codes are not deemed acceptable in [plain text output](https://github.com/jenkinsci/jenkins/blob/9fce1ee933eb5276baff977d562fc8e183f1c8d6/core/src/main/java/hudson/console/PlainTextConsoleOutputStream.java#L38) (not sure where that is used), then it would be possible to convert all ansi codes to ConsoleNotes, and have them return a new ConsoleAnnotator from their annotate function. There is some funky code [here](https://github.com/jenkinsci/jenkins/blob/31ad77005ea1cb9ab07e2312b6dadd1eb15ab72b/core/src/main/java/hudson/console/ConsoleAnnotationOutputStream.java#L110) and [here](https://github.com/jenkinsci/jenkins/blob/31ad77005ea1cb9ab07e2312b6dadd1eb15ab72b/core/src/main/java/hudson/console/ConsoleAnnotator.java#L94) that maintains as many ConsoleAnnotators as get created. So for each Ansi code a ConsoleAnnotator would be generated that gets fed all lines until it finds a closing Ansi code, emits it's html close tag and nullifies itself (returning null from annotate). Unbelievable, that someone seriously came up with this truly Javaish™ design. Of course the many ConsoleAnnotator instances can not share data between each other (the context argument to annotate is something else).

I don't see a big use case for plain text output (the on-disk format would contain ANSI concealed bytes anyhow) and it could be easily communicated, that the ansi-color plugin only works w/ html output. In fact when logging with color to a raw output, I'd expect to see `ESC[32m` all over the place.
So the simplest and most maintainable solution is to add a AnsiColorAnnotator that keeps track of ansi state and produces html on the fly.

**Comment by MartinNowak** [comment]
Well, that was fairly straightforward to do.
[rewrite plugin as simple ConsoleAnnotator](https://github.com/MartinNowak/jenkins-ansicolor-plugin/commit/2f8a70d558f5097879bac6ddc8dd3fb1485ce261)
Now if you could find out how to make the ConsoleAnnotator configurable, i.e. wire it up w/ the old [BuildWrapperDescriptor](https://github.com/MartinNowak/jenkins-ansicolor-plugin/commit/2f8a70d558f5097879bac6ddc8dd3fb1485ce261#diff-dcd2ed331bdbfe60b844128df2eb06dbL92), then we almost have a working plugin :).

**Comment by MartinNowak** [comment]
During [instantiation](https://github.com/MartinNowak/jenkins-ansicolor-plugin/commit/2f8a70d558f5097879bac6ddc8dd3fb1485ce261#diff-f5ab977b3812509864501d114029ff48R16) the model context in which it is instantiated is passed, e.g. a hudson.FreeStyleBuild. Maybe it's possible to get config data from there?

**Comment by jmmk** [comment]
Ran into this after adding AnsiColor to some jobs. Our disk very quickly filled up as the logs are ~100x bigger. The color output is nice, but not worth the disk space.

**Comment by jakubjosef** [comment]
I created a pure JS version, because we really want to have colorised output.
Enjoy! https://github.com/jakubjosef/jenkins-ansi-color-js

**Comment by dblock** [comment]
@jakubjosef Very nice. You could use this plugin as a skeleton to build a proper Jenkins plugin out of it.

**Comment by stevekuznetsov** [comment]
Has this somehow been baked into the Jenkins pipeline code? We've expressly disabled the ANSI color plugin from all of our jobs since this was making our raw logs unreadable, but now I see the same output for `[Pipeline]` prefixes in Jenkinsfile jobs:

```
/KF0vKzUvOzOvODlTryCnNB3I0ivPL8pOy8kv18vKT9JLzs8rzs9J1QuHCgaV5jlDhPzyS1IZIICRiYGhoohBKqM0pTg/D64Hh8ICAFt0h+h/AAAA[0m[Pipeline] }
[8mha:////4KrvCB5f7OMA9h/W+dpZJxegNMjvsI0uJTVtGCxubMyMAAAAaB+LCAAAAAAAAP9b85aBtbiIwTG/KF0vKzUvOzOvODlTryCnNB3I0ivPL8pOy8kv18vKT9JLzs8rzs9J1QuHCgaV5jlDhPzyS1IZIICRiYGhoohBKqM0pTg/D64Hh8ICAFt0h+h/AAAA[0m[Pipeline] // stage
[8mha:////4KrvCB5f7OMA9h/W+dpZJxegNMjvsI0uJTVtGCxubMyMAAAAaB+LCAAAAAAAAP9b85aBtbiIwTG/KF0vKzUvOzOvODlTryCnNB3I0ivPL8pOy8kv18vKT9JLzs8rzs9J1QuHCgaV5jlDhPzyS1IZIICRiYGhoohBKqM0pTg/D64Hh8ICAFt0h+h/AAAA[0m[Pipeline] stage
```

**Comment by JoeMerten** [comment]
@MartinNowak, @jakubjosef: You might try out my [AnsiColors.py](https://github.com/JoeMerten/Jfe/blob/master/Framework/tools/AnsiColors.py) to create various Ansi Codes for testing your implementations. Feedback is welcome.

**Comment by trim777** [comment]
Please, help

I have the same issue on Jenkins ver. 2.176.1, Timestamper 1.10 and AnsiColor 0.6.2 plugins.

**Comment by tszmytka** [comment]
Since at least `v0.6.3` the plugin uses `ConsoleAnnotator` as the main way of influencing the log output. Some `ConsoleNote` s are still necessary in situations like having multiple `ansiColor('xterm')` steps in your pipeline but most builds should contain not more than 3 such notes which I think is very reasonable.
