### ISSUE TITLE
Update description @ https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

### ISSUE THREAD

**Issue by karlhaas** [jenkinsci/ansicolor-plugin#70]
It's the first time that I use Pipeline, Jenkinsfile and the ansicolor plugin. It was very difficult for me to figure out how to add the plugin to the Jenkinsfile. Finally I found the solution here on github.
The problem was that the information on the official plugin page looks like the same as in the Readme but the part about how to add the plugin to the Jenkinsfile is missing.

I think there would be 2 possible solutions:
- remove the information from the official plugin page and just link to the Readme
- or keep the official plugin page up-to-date

Also the script generator did not help. It generates:
`wrap(<object of type hudson.plugins.ansicolor.AnsiColorBuildWrapper>) {
    // some block
}`

**Comment by dblock** [comment]
The "official" plugin page should be up-to-date automatically with every release, but I haven't followed the release process for a while, someone else can comment.

**Comment by JoeMerten** [comment]
For some reason, there are 2 different plugin pages:
- https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin
- https://plugins.jenkins.io/ansicolor

and I also don't understand the sync procedure until now.
For the former, it seems that the wiki page needs to be maintained manually (I'd just updated the links because of the recent repo migration).
But for the latter, I have no idea. Today, it still shows `0.4.3` as current version, even if the `0.5.0` has been released two days ago.

For snippet generator, see also #65.

**Comment by dblock** [comment]
I think they just sync it occasionally.

**Comment by JoeMerten** [comment]
Both wiki pages are in sync now (see also https://github.com/jenkins-infra/jenkins-infra/pull/706) and both containing IMHO helpful Jenkinsfile codesnippets now.
